#!/usr/bin/env python3
"""
generate_report.py
------------------
Converts klocwork_report.json into a human-readable Markdown report.

Usage:
    python3 scripts/generate_report.py \
        --report klocwork_report.json \
        --output klocwork_report.md
"""

import argparse
import json
from datetime import datetime
from pathlib import Path


SEV_LABEL = {1: "🔴 CRITICAL", 2: "🟠 ERROR", 3: "🟡 WARNING", 4: "🔵 REVIEW"}
SEV_NAME  = {1: "Critical", 2: "Error", 3: "Warning", 4: "Review"}


def build_markdown(report: dict) -> str:
    summary = report.get("summary", {})
    issues  = report.get("issues", [])
    by_sev  = summary.get("by_severity", {})
    now     = datetime.now().strftime("%Y-%m-%d %H:%M")

    lines = [
        "# Klocwork Static Analysis Report",
        "",
        f"**Generated:** {now}  ",
        f"**Base ref:**  `{summary.get('base', 'N/A')}`  ",
        f"**Head ref:**  `{summary.get('head', 'N/A')}`  ",
        "",
        "## Summary",
        "",
        "| Severity | Count |",
        "|----------|-------|",
        f"| 🔴 Critical (1) | {by_sev.get('1_critical', 0)} |",
        f"| 🟠 Error    (2) | {by_sev.get('2_error',    0)} |",
        f"| 🟡 Warning  (3) | {by_sev.get('3_warning',  0)} |",
        f"| 🔵 Review   (4) | {by_sev.get('4_review',   0)} |",
        f"| **Total**       | **{summary.get('total_issues', len(issues))}** |",
        "",
        f"Files analysed: **{summary.get('files_analysed', 0)}**",
        "",
    ]

    if not issues:
        lines += ["## Issues", "", "_No issues found._", ""]
        return "\n".join(lines)

    # Group by file
    by_file: dict[str, list[dict]] = {}
    for issue in issues:
        fp = issue.get("file", "unknown")
        by_file.setdefault(fp, []).append(issue)

    lines.append("## Issues by File")
    lines.append("")

    for fp, file_issues in sorted(by_file.items()):
        lines.append(f"### `{fp}`")
        lines.append("")
        for iss in sorted(file_issues, key=lambda x: (x.get("severity",9), x.get("line",0))):
            sev   = iss.get("severity", 0)
            label = SEV_LABEL.get(sev, "⚪ UNKNOWN")
            lines += [
                f"#### {label} — `{iss.get('checker', 'UNKNOWN')}`",
                "",
                f"- **Line:** {iss.get('line', '?')}  ",
                f"- **Description:** {iss.get('description', '')}  ",
                f"- **Fix:** {iss.get('fix_description', '')}",
                "",
            ]
            snippet = iss.get("code_snippet", "").strip()
            fix     = iss.get("fixed_code",   "").strip()
            if snippet:
                lines += [
                    "**Problematic code:**",
                    "```cpp",
                    snippet,
                    "```",
                    "",
                ]
            if fix and fix != snippet:
                lines += [
                    "**Suggested fix:**",
                    "```cpp",
                    fix,
                    "```",
                    "",
                ]
            lines.append("---")
            lines.append("")

    lines += [
        "## How to apply fixes",
        "",
        "Run the fix applicator (dry-run first to review):",
        "",
        "```bash",
        "# Preview all severity-1 and severity-2 fixes",
        "python3 scripts/apply_fixes.py --report klocwork_report.json --dry-run",
        "",
        "# Apply severity-1 (critical) fixes only",
        "python3 scripts/apply_fixes.py --report klocwork_report.json --severity 1",
        "",
        "# Apply with interactive confirmation",
        "python3 scripts/apply_fixes.py --report klocwork_report.json --severity 1,2 --interactive",
        "",
        "# Review what changed (fixes are left UNSTAGED)",
        "git diff",
        "",
        "# Selectively stage hunks",
        "git add -p",
        "```",
        "",
        "_Report generated by SDLC Automation – Klocwork Analysis Module_",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate Markdown report from Klocwork JSON")
    parser.add_argument("--report", default="klocwork_report.json")
    parser.add_argument("--output", default="klocwork_report.md")
    args = parser.parse_args()

    report = json.loads(Path(args.report).read_text())
    md = build_markdown(report)
    Path(args.output).write_text(md, encoding="utf-8")
    print(f"[DONE] Report written to {args.output}")


if __name__ == "__main__":
    main()
